name: iOS Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Decode Certificates
        run: |
          echo ${{ secrets.IOS_P12_BASE64 }} | base64 --decode > ios_distribution.p12
          echo ${{ secrets.IOS_PROV_PROFILE_BASE64 }} | base64 --decode > provisioning_profile.mobileprovision

      - name: Build iOS App
        run: |
          xcodebuild -workspace ios/YourApp.xcworkspace \
                     -scheme YourAppScheme \
                     -configuration Release \
                     -archivePath $PWD/build/YourApp.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/YourApp.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MyApp.ipa
          path: ./build/*.ipa
